// ============================================================
// ClearanceHub — Auto-Generated Deal Data
// Last updated: 2026-09-22 by GitHub Actions
// Sources: DealNews category RSS · Slickdeals clearance search
// ============================================================

const DEALS = [
  {
    id:             1,
    name:           "Kohl\\'s: Select Lego Sets 20% Off + $10 off $50+: Disney\\'s Lilo & Stitch (43249) $42 & More",
    category:       "toys",
    retailer:       "amazon",
    normalPrice:    50,
    clearancePrice: 10,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Kohl's%3A%20Select%20Lego%20Se",
    link:           "https://slickdeals.net/f/20041989-kohls-10-off-50-toys-coupon-lego-extravaganza-more?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             2,
    name:           "Victoria\\'s Secret Women\\'s Panties (Various) 5",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    50,
    clearancePrice: 20,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Victoria's%20Secret%20Wome",
    link:           "https://slickdeals.net/f/20033838-victoria-s-secret-big-fall-sale-panties-5-for-20-3-99?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             3,
    name:           "40-Lb CAP Barbell Adjustable Weighted Vest w/ Removable Weight Packets $37.35 + Free S&H on $49+",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    49,
    clearancePrice: 37.35,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=40-Lb%20CAP%20Barbell%20Adju",
    link:           "https://slickdeals.net/f/20033826-40-lb-cap-barbell-adjustable-weighted-vest-37-35-free-shipping-on-49?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             4,
    name:           "B1G1: 8-pc Comforter Sets (various) 2",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    39,
    clearancePrice: 29.95,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=B1G1%3A%208-pc%20Comforter%20S",
    link:           "https://slickdeals.net/f/20014554-buy-one-get-one-two-8-piece-comforter-sets-various-any-size-29-93-14-96-each-3-piece-23-93-free-pickup-at-macys-or-free-shipping-on-39?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             5,
    name:           "Vibrant Life 11\" Holiday Highland Cow w/ Present Plush Dog Toy (Brown/Red) $2.40 + Free S&H on $35+",
    category:       "toys",
    retailer:       "walmart",
    normalPrice:    35,
    clearancePrice: 2.4,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=Vibrant%20Life%2011%22%20Holid",
    link:           "https://slickdeals.net/f/20014338-vibrant-life-11-holiday-highland-cow-plush-dog-toy-2-39-free-shipping-w-walmart-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             6,
    name:           "Cooler Master Q300L V1 Micro-ATX High Airflow PC Case $35 + Free S&H",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    39.99,
    clearancePrice: 35,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Cooler%20Master%20Q300L%20V1",
    link:           "https://slickdeals.net/f/20004621-ac-34-98-cooler-master-masterbox-q300l-microatx-tower-pc-case-w-magnetic-dust-filter-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             7,
    name:           "Nike Vapor 16/Phantom 6 Academy D-Width Soccer Cleats (various colors) $22.50 + Free S&H on $25+",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    25,
    clearancePrice: 22.5,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Nike%20Vapor%2016%2FPhantom%20",
    link:           "https://slickdeals.net/f/19992495-nike-vapor-16-phantom-6-academy-d-width-soccer-cleats-various-colors-22-50-free-s-h-on-25?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             8,
    name:           "Backpack Clearance Sale: Wonder Nation Kids\\' 17\" Backpack (Various) $2 & More",
    category:       "supplies",
    retailer:       "walmart",
    normalPrice:    12.79,
    clearancePrice: 2,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=Backpack%20Clearance%20Sal",
    link:           "https://slickdeals.net/f/19990230-backpack-clearance-sale-wonder-nation-kids-17-backpack-various-2-more?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             9,
    name:           "Lucid 2\" Cooling Gel Aloe Vera Plush Memory Foam Mattress Topper (Twin XL Size) $16.95 + Free S&H on $35+",
    category:       "home",
    retailer:       "walmart",
    normalPrice:    35,
    clearancePrice: 16.95,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=Lucid%202%22%20Cooling%20Gel%20A",
    link:           "https://slickdeals.net/f/19973970-lucid-2-cooling-gel-with-aloe-plush-memory-foam-mattress-topper-twin-xl-16-94?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  }
];
