// ============================================================
// ClearanceHub — Auto-Generated Deal Data
// Last updated: 2026-07-24 by GitHub Actions
// Sources: DealNews category RSS · Slickdeals clearance search
// ============================================================

const DEALS = [
  {
    id:             1,
    name:           "25.4oz. Splenda Sugar Free Flavored Liquid Syrup (French Vanilla) $2.85 w/ S&S",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    3.02,
    clearancePrice: 2.85,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=25.4oz.%20Splenda%20Sugar%20",
    link:           "https://slickdeals.net/f/19795203-new-sns-2-87-25-4-oz-splenda-coffee-syrup-french-vanilla-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             2,
    name:           "2-Pk Athletic Works 9\" Dri Mid Rise Bike Shorts (various colors/sizes) $5 + Free S&H on $35+",
    category:       "sports",
    retailer:       "walmart",
    normalPrice:    35,
    clearancePrice: 5,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=2-Pk%20Athletic%20Works%209%22",
    link:           "https://slickdeals.net/f/19792332-2-pack-athletic-works-women-s-mid-rise-9-bike-shorts-3-colors-5-free-s-h-w-walmart-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             3,
    name:           "32 Degrees Summer Clearance Sale: Men\\'s Cool Crew T-Shirt $5 + Free S&H $23.75+",
    category:       "fashion",
    retailer:       "amazon",
    normalPrice:    23.75,
    clearancePrice: 5,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=32%20Degrees%20Summer%20Clea",
    link:           "https://slickdeals.net/f/19786203-32-degrees-summer-clearance-sale-men-s-cool-crew-t-shirt-4-99-more-free-shipping-on-24?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             4,
    name:           "20-Pc Skil Sanders Mixed 5\" Round Sanding Paper Kit (60/80/120/240 Grits)",
    category:       "supplies",
    retailer:       "walmart",
    normalPrice:    35,
    clearancePrice: 4.9,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=20-Pc%20Skil%20Sanders%20Mix",
    link:           "https://slickdeals.net/f/19782918-4-90-skil-20-piece-mixed-5-in-60-80-120-240-grits-round-sanding-paper-kit-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             5,
    name:           "Dog Fetch Balls, Toys, & More Clearance: 2-Pk 2\" Chuckit! Erratic Ball Fetch Toy $1.25 & More",
    category:       "toys",
    retailer:       "walmart",
    normalPrice:    3.85,
    clearancePrice: 1.25,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=Dog%20Fetch%20Balls%2C%20Toys%2C",
    link:           "https://slickdeals.net/f/19782633-clearance-chew-king-chuck-it-more-dog-toys-89-0-89?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             6,
    name:           "Walmart Kids\\' Room Clearance: Cocomelon LED Canvas Wall Art (15.75\" x 11.5\") $2.40 & More",
    category:       "supplies",
    retailer:       "walmart",
    normalPrice:    17.49,
    clearancePrice: 2.4,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=Walmart%20Kids'%20Room%20Cle",
    link:           "https://slickdeals.net/f/19781052-walmart-kids-room-clearance-cocomelon-led-canvas-wall-art-15-75-x-11-5-2-40-more?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             7,
    name:           "Select Lowe\\'s Stores: Police Security Elite Skylar 3300-Lumens LED Flashlight $12.50 + Free Pickup Only",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    12.52,
    clearancePrice: 12.5,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Select%20Lowe's%20Stores%3A%20",
    link:           "https://slickdeals.net/f/19777269-ymmv-police-security-skylar-3300-lumen-5-adjustable-mode-led-flashlight-one-size-98409tm-12-52?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             8,
    name:           "Old Navy Clearance Sale: Women\\'s, Men\\'s & Kids\\' Apparel & More up to 85% OFF + Free S&H on $50+",
    category:       "fashion",
    retailer:       "amazon",
    normalPrice:    333.33,
    clearancePrice: 50,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Old%20Navy%20Clearance%20Sal",
    link:           "https://slickdeals.net/f/19774758-up-to-85-off-old-navy-clearance-sale?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             9,
    name:           "Gap Factory Sale: 55% Off Select Clearance Items & More + Get an Extra 15% Off + Free S&H on $50+",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    111.11,
    clearancePrice: 50,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Gap%20Factory%20Sale%3A%2055%25%20",
    link:           "https://slickdeals.net/f/19770798-up-to-72-off-extra-55-off-extra-15-off-gap-factory-clearance-sale?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             10,
    name:           "Nike Men\\'s Air Max SC Shoes (White/Gold) $54.35 + Free S&H",
    category:       "fashion",
    retailer:       "amazon",
    normalPrice:    54.37,
    clearancePrice: 54.35,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Nike%20Men's%20Air%20Max%20SC%20",
    link:           "https://slickdeals.net/f/19769469-nike-men-s-air-max-sc-shoes-white-gold-leaf-photon-dust-54-37-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  }
];
