// ============================================================
// ClearanceHub — Auto-Generated Deal Data
// Last updated: 2026-07-06 by GitHub Actions
// Sources: DealNews category RSS · Slickdeals clearance search
// ============================================================

const DEALS = [
  {
    id:             1,
    name:           "REI 4th of July Deals Event: Clothing, Footwear, Travel Gear & More Up to 50% Off + Free Pickup",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    120,
    clearancePrice: 60,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=REI%204th%20of%20July%20Deals%20",
    link:           "https://slickdeals.net/f/19720392-up-to-79-off-rei-4th-of-july-sale?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             2,
    name:           "Eddie Bauer Clearance Sale: Women\\'s, Men\\'s and Kids\\' Apparel (Various) up to 60% Off + Free S&H on $99+",
    category:       "fashion",
    retailer:       "amazon",
    normalPrice:    247.5,
    clearancePrice: 99,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Eddie%20Bauer%20Clearance%20",
    link:           "https://slickdeals.net/f/19719033-eddie-bauer-clearance-up-to-60-off-4th-of-july-sale?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             3,
    name:           "Bath & Body Works Clearance Sale: 75% Off Select Items: Candles $4.25, Wallflowers $2 & More + Free Pickup",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    4.48,
    clearancePrice: 4.25,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Bath%20%26%20Body%20Works%20Clea",
    link:           "https://slickdeals.net/f/19718940-bath-body-works-clearance-sale-75-off-select-items-candles-4-25-wallflowers-2-more-free-pickup?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             4,
    name:           "Crocs Extra Savings: Select Accessories 40% Off, Sale Style Footwear 30% Off + Free S&H on $50+",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    83.33,
    clearancePrice: 50,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Crocs%20Extra%20Savings%3A%20S",
    link:           "https://slickdeals.net/f/19710732-crocs-extra-30-off-clearance-footwear-40-off-select-accessories-free-shipping-on-49-99?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             5,
    name:           "Cooler Master Elite 301 Lite Micro-ATX Computer Case (Black) $40 + Free S&H w/ Amazon Prime",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    49.99,
    clearancePrice: 40,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Cooler%20Master%20Elite%2030",
    link:           "https://slickdeals.net/f/19708275-cooler-master-elite-301-lite-micro-atx-high-airflow-minimalist-pc-case-40-free-s-h-w-prime-at-woot?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             6,
    name:           "Select Stores: DeWALT 20V MAX XR POWERSTACK Li-Ion Kit w/ 3.5Ah Battery & Charger",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    60.02,
    clearancePrice: 60,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Select%20Stores%3A%20DeWALT%20",
    link:           "https://slickdeals.net/f/19706139-ymmv-20v-max-xr-powerstack-lithium-ion-battery-starter-kit-with-3-5ah-battery-and-charger-60-at-home-depot?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             7,
    name:           "Solati Cordless Hair Clipper & Beard Trimmer Kit w/ LED Display",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    29.99,
    clearancePrice: 17.7,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Solati%20Cordless%20Hair%20C",
    link:           "https://slickdeals.net/f/19700700-solati-cordless-hair-clipper-beard-trimmer-kit-w-led-display-black-17-69-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             8,
    name:           "Old Navy Apparel for the Family: 50% Off Everything + Free S&H on $50+",
    category:       "fashion",
    retailer:       "amazon",
    normalPrice:    100,
    clearancePrice: 50,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=Old%20Navy%20Apparel%20for%20t",
    link:           "https://slickdeals.net/f/19682781-50-off-everything-old-navy-clearance-apparel-for-the-family?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             9,
    name:           "4\\' RealPlay Jumbo Oversized 4-in-a-Row Connect Game w/ 42x Rings $44.85 + Free S&H",
    category:       "supplies",
    retailer:       "walmart",
    normalPrice:    44.86,
    clearancePrice: 44.85,
    fallbackImage:  "https://placehold.co/300x200/0071ce/ffffff?text=4'%20RealPlay%20Jumbo%20Over",
    link:           "https://slickdeals.net/f/19678536-4-realplay-jumbo-4-in-a-row-connect-game-w-42-rings-44-86-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             10,
    name:           "REI: Past Season Clearance Sale up to 77% Off + Free Pickup",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    260.87,
    clearancePrice: 60,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=REI%3A%20Past%20Season%20Clear",
    link:           "https://slickdeals.net/f/19677150-up-to-77-off-rei-past-season-clearance-deals?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  },
  {
    id:             11,
    name:           "REI 4th of July Deals Event: Up to 50% Off Clearance, Sale & More: See Thread For Deals + Free S&H on $60+",
    category:       "supplies",
    retailer:       "amazon",
    normalPrice:    120,
    clearancePrice: 60,
    fallbackImage:  "https://placehold.co/300x200/ff9900/ffffff?text=REI%204th%20of%20July%20Deals%20",
    link:           "https://slickdeals.net/f/19662150-rei-4th-of-july-sale-huge-discounts-on-select-apparel-hiking-boots-and-outdoor-gear-starts-june-26?utm_source=rss&utm_content=fp&utm_medium=RSS2",
    inStock:        true,
    badge:          "Clearance",
  }
];
